<?php

$school = array( array( ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                          ["name" =>'sasha',"lastname" =>'sergienko'],
                        ),
                array(  ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                            ["name" =>'vitalic',"lastname" =>'kochevenko'],
                    ),
                    array(  ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                ),
                array(  ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
            ),
            array(  ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
                            ["name" =>'sasha',"lastname" =>'sergienko'],
        ),
                    );


echo "<pre>";
print_r($school);
echo "</pre>"."<br>";